### ISSUE TITLE
Vote RPC：error: {"code":-8,"message":"Property identifier is out of range"}

### ISSUE THREAD

**Issue by Ankarrr** [m04120310/omnicore#9]
範例：
omnicli gcoin_vote_for_license "mjZe4haCrjUcDHdGuX5kBn6sNhv65QTTRc" 2147483651 "approve"
RPCConvertValues strMethod:gcoin_vote_for_license

Result：
strParams: mjZe4haCrjUcDHdGuX5kBn6sNhv65QTTRc
method: gcoin_vote_for_license
strParams: 2147483651
method: gcoin_vote_for_license
strParams: approve
method: gcoin_vote_for_license
error: {"code":-8,"message":"Property identifier is out of range"}

**Comment by m04120310** [comment]
我正在研究，稍待一下
